### ISSUE TITLE
NotoireCreateLink idea

### ISSUE THREAD

**Issue by justinmoon** [KevinBockelandt/notoire#22]
Great plugin!

Currently, `NotoireCreateLink` requires a visual selection to work.

I suggest that if there isn't a visual selection, you could just insert the link with empty description. For example, choosing the note with ID 6 would produce this:

```
[](6)
```

Stick the cursor between the square brackets to more quickly write the description.

**Comment by KevinBockelandt** [comment]
Hi, good idea! I created a method called :NotoireCreateEmptyLink to do that. The [default mapping](https://github.com/KevinBockelandt/notoire#setup) was updated to make it more consistent.

Tell me what you think about it :)

**Comment by KevinBockelandt** [comment]
I'm assuming it's OK, if you need more info please open another issue.
