### ISSUE TITLE
NotoireCreateNote could accept visual selection

### ISSUE THREAD

**Issue by justinmoon** [KevinBockelandt/notoire#23]
If some idea in a note would make a good "note" itself, I currently have

1. `NotoireCreateNote` to create a new note
2. Go back to previous note
3. Visually the text I want to turn into a link 
4. `NotoireCreateLink` to create the link

Would be nice if I could just do `3` and then `1`.

**Comment by KevinBockelandt** [comment]
Hi, I changed the method :NotoireCreateNote to behave in this way. You need to visually select the content of the new note then call the method. The visual selection will be deleted from the initial note and pasted into the new one, a link will be placed instead in the initial note.

The [default mapping](https://github.com/KevinBockelandt/notoire#setup) changed to make it more consistent.

Tell me what you think about it :)

**Comment by KevinBockelandt** [comment]
I'm assuming it's OK, if you need more info please open another issue.
