### ISSUE TITLE
How to change default file extension?

### ISSUE THREAD

**Issue by anthrolisp** [KevinBockelandt/notoire#25]
How to change default file extension? I'd like to change it to md and/ org
Many thanks in advance!

**Comment by KevinBockelandt** [comment]
Hi, I've added the [`g:notoire_file_extension`](https://github.com/KevinBockelandt/notoire/blob/master/doc/notoire.txt#L118) option in order to choose the extension you prefer.

Thanks for the feedback! :)

Done with commit 4db95df2d0e3681e99dfa1819b40d6b46bd34183
