### ISSUE TITLE
g:notoire_folder requires a tailing slash

### ISSUE THREAD

**Issue by A** [KevinBockelandt/notoire#26]
Hi! I just started to play with this pretty nice tool, and i spend half of hour to figure out why everything isn't working properly. Then i've got that I hadn't added a tailing slash to `notoire_folder`. Not a critical thing, but it would be nice to normalize path inside of the plugin, and don't leave it to user.

```
The mandatory option *g:notoire_folder* defines the path to the folder
containing the notes. Exemple:
>
    let g:notoire_folder = '~/Dropbox/notoire/'
```

**Comment by KevinBockelandt** [comment]
Hi, thanks for pointing that out!

It is now fixed so you can use `g:notoire_folder` with or without a tailing slash.
