### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by voider1** [KevinBockelandt/notoire#27]
I was reading about how to use a Zettelkasten and one thing I noticed is tagging. How would you handle tagging in this system?

**Comment by KevinBockelandt** [comment]
Hi, there is no specific built-in feature for tags with this plugin.

You could simply add tags in text form as part of your notes. For exemple:

```
#tag1 #tag2

# My note title

The note content
```

And then search them through the regular search process.

**Comment by voider1** [comment]
I'd like to propose a new feature which shows notes based on tags. E.g.:
```
tags: #mobile #android
tags: #mobile #android #crypto
tags: #mobile #ios
```

Say I wanna filter on mobile and android, I could do the following:
```sh
rg #mobile | rg #android | cut -d':' -f1
```

**Comment by KevinBockelandt** [comment]
To be honest, I'm not too happy with the current way of searching through notes. For example, the lack of color in the results makes them difficult to read, and that issue cannot be solved easily.

I'm exploring different ideas on how to improve the whole thing but my point is that in time the current way of doing things will probably be obsolete.

In the meantime you can just do a regular search in which you add the keywords corresponding to the tags you're looking for. Ex: `#mobile #android content I look for`.

FZF will be able to give you the corresponding notes

**Comment by voider1** [comment]
How would you like to change the way it works? I was thinking about doing a rewrite in Lua and adding a built-in tagging mechanism.

**Comment by KevinBockelandt** [comment]
Mainly the presentation of the results is problematic. The list of potential notes is difficult to read and the preview of the currently selected note is not great either.

But again I don't think there is any easy way to fix this. The problem comes from vim itself which is not well suited for this kind of things.

Doing things in Lua is definitely a good idea. Vimscript is a pain to work with.

**Comment by voider1** [comment]
Wouldn't it be possible to leverage the floating windows and the terminal emulator built-in Neovim to get this to work? I think you could make pretty neat interfaces.

**Comment by KevinBockelandt** [comment]
I don't know enough about the specific features of Neovim to know what is possible or not. But it is definitely an interesting lead to look at.

Whatever the case I suspect it will involve a significant amount of work and unfortunately I don't have a lot of time to work on this project at the moment.

But please let me know if you make progress with this. I'm interested to see the result!

**Comment by KevinBockelandt** [comment]
Closing this issue for now. Please let me know if you move on with a re-write in Lua, it seems like a good idea. :)
