### ISSUE TITLE
`notoire_file_extension` is not used when creating links

### ISSUE THREAD

**Issue by nakedpony** [KevinBockelandt/notoire#30]
When I set up notoire_file_extension = 'md' and create a new zettel with `:NotoireCreateLink` it creates link like the following `[second one](2)` which is not a valid link when commiting this to github. Is there a possibility to create the link with the extension like this: `[second one](2.md)`? Thank you.

**Comment by KevinBockelandt** [comment]
Hello,

I'm not sure what you mean by "it's not a valid link committing this to github".

It is the intended behavior that no file extension is displayed in the notes (for clarity). It's all handled internally.

Is there something you want to achieve in particular with the file extensions?

**Comment by nakedpony** [comment]
Hello Kevin,

Sorry for not making it clear. So I created a test repository on github to show it: https://github.com/nakedpony/zettel
If you click first link from README.md it will not work, but the second one will.

Thanks!

**Comment by KevinBockelandt** [comment]
Thanks I see now. I added an option to add the file extension in the links: https://github.com/KevinBockelandt/notoire/blob/5dd9b3f4e94eef1bd220699ca386118b6dcbf260/doc/notoire.txt#L140

Beware though that links should be consistent. All of them without extensions or all of them with extensions and the option active. If they are mixed some search features of Notoire will not work properly.

Tell me if that's ok with you :)

**Comment by nakedpony** [comment]
Hey Kevin,

Thank you so much for making changes so quickly. It works perfectly now!

Cheers, 
Sergey.
