### ISSUE TITLE
`:NotoireCreateLink` doesn't correctly link in nvim

### ISSUE THREAD

**Issue by pgronkievitz** [KevinBockelandt/notoire#32]
after selecting text it's not linking correctly. There's only opening square bracket and selected text, but no closing and link per se.

example on asciinema
[![asciicast](https://asciinema.org/a/Ct9Q0u9lawvc1smqrMGlvTAAF.svg)](https://asciinema.org/a/Ct9Q0u9lawvc1smqrMGlvTAAF)

**Comment by pgronkievitz** [comment]
#33 will solve it

**Comment by KevinBockelandt** [comment]
PR merged. Thanks for fixing this issue!
